### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ShalokShalom** [SGOrava/Unloader#1]
How to install?

**Comment by SGOrava** [comment]
With current development version of Falkon:
> Go to https://store.falkon.org/p/1307514/ press `Install` and follow instructions.

Or copy the unloader directory into `~/.config/falkon/plugins/`

With older Falkon it needs to be copied into install path which looks something like this:
`/usr/lib/qt/plugins/falkon/python/`
It will only work if Python support is enabled and functional.

I considered this repository only as a place for data so I did not include installation manual.

**Comment by ShalokShalom** [comment]
Wow, I didnt know that Falkon has an app store now :open_mouth:
